/*
 * Copyright (c) 2026-present, Intechcore GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.intechcore.scomponents.tools.cutter.annotations.common;

import com.intechcore.scomponents.tools.cutter.annotations.CutCode;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * The {@code @CutCodes} is a container annotation for {@link CutCode}.
 * It allows multiple {@code @CutCode} annotations to be applied to the same method,
 * enabling complex code cutting and replacement scenarios.
 * This annotation is automatically generated by the Java compiler when
 * {@link CutCode} is used multiple times on a single element due to its
 * {@link java.lang.annotation.Repeatable} nature.
 *
 * @see CutCode
 */
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.SOURCE)
public @interface CutCodes {
    /**
     * An array of {@link CutCode} annotations.
     *
     * @return An array of {@link CutCode} annotations.
     */
    CutCode[] value();
}
